CREATE TABLE IF NOT EXISTS big3_records (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  bench_press DECIMAL(6,2) NULL,
  squat DECIMAL(6,2) NULL,
  deadlift DECIMAL(6,2) NULL,
  recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_big3_records_user_id (user_id),
  CONSTRAINT fk_big3_records_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
